import dotenv from "dotenv";

dotenv.config();

const ENV = {
  PORT: process.env.PORT || 3000,
  NODE_ENV: process.env.NODE_ENV || "development",
  CORS_ORIGIN: process.env.CORS_ORIGIN || "*",

  MESSAGE_CENTRAL_BASE_URL:
    process.env.MESSAGE_CENTRAL_BASE_URL || "https://cpaas.messagecentral.com",
  MESSAGE_CENTRAL_CUSTOMER_ID: process.env.MESSAGE_CENTRAL_CUSTOMER_ID || "C-D74580EA96564FF",
  MESSAGE_CENTRAL_KEY: process.env.MESSAGE_CENTRAL_KEY || "",
  MESSAGE_CENTRAL_AUTH_TOKEN: process.env.MESSAGE_CENTRAL_AUTH_TOKEN || "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJDLUQ3NDU4MEVBOTY1NjRGRiIsImlhdCI6MTc3ODk0NzE0MywiZXhwIjoxOTM2NjI3MTQzfQ.LDqA3UxsAEMXwDZWT5rxIi-CshBiyL-2kGsC7zHo9TNPfJ3igSCeK7xHy6f27MtSkEBfEVpPsuhEbHgcDGsmfQ",
  MESSAGE_CENTRAL_DEFAULT_COUNTRY_CODE:
    process.env.MESSAGE_CENTRAL_DEFAULT_COUNTRY_CODE || "91",
  MESSAGE_CENTRAL_FLOW_TYPE: process.env.MESSAGE_CENTRAL_FLOW_TYPE || "SMS",
  MESSAGE_CENTRAL_OTP_LENGTH: Number(process.env.MESSAGE_CENTRAL_OTP_LENGTH) || 6,
};

export default ENV;
